apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: my-database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 32000 
  type: NodePort
