apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-database
    spec:
      containers:
      - image: mysql:8.0
        name: mysql-container
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "willys_password"
        ports:
        - containerPort: 3306
          name: mysql-port
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc